[package]
name = "hi-wallet"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

# [lib]
# path = "src/lib.rs"

[[bin]]
name = "calculator"
path = "src/calculator/main.rs"

[dependencies]
calculate = "0.5.1"
chrono = "0.4"
html5ever = "0.15"
hyper-rustls = "0.6"
mime_guess = "1.8"
mime = "0.2"
orbclient = "0.3.20"
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont" }
orbimage = "0.1"
orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk" }
tendril = "0.4"
url = "1.5"
redox_users = "0.2"
