[package]
name = "hi-wallet"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

# [lib]
# path = "src/lib.rs"

[[bin]]
name = "calculator"
path = "src/calculator/main.rs"

[[bin]]
name = "prototype"
path = "src/prototype/main.rs"

[[bin]]
name = "wallet0"
path = "src/wallet0/main.rs"


[dependencies]
calculate = "0.5.1"
orbclient = "0.3.20"
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont" }
orbimage = "0.1"
orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk" }


[patch."https://gitlab.redox-os.org/redox-os/orbtk"]
orbtk = { path = "../orbtk" }