[package]
name = "hi-wallet"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

[[bin]]
name = "launcher"
path = "src/main.rs"

[lib]
name = "hi_wallet"
path = "src/lib.rs"

# [dependencies]
# tweek-rust = { path = "../tweek-rust" }

